import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

import Changelog from '@/components/changelog';
import Navbar from '@/components/Navbar';
import Hero from '@/components/Hero';
import Services from '@/components/Services';
import OurGoal from '@/components/OurGoal';
import Footer from '@/components/Footer';
import HowItWorks from '@/components/HowItWorks';
import JoinWaitlist from '@/components/JoinWaitlist';
import ForWhom from '@/components/ForWhom';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Seomind</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Bruno+Ace+SC&family=Dancing+Script&family=Montserrat:wght@200;700&family=Nunito+Sans:wght@300;400;600&family=Pacifico&family=Permanent+Marker&family=Raleway:wght@700&family=Rubik+Iso&family=Ubuntu&display=swap" />
      </Head>
      
      <main className="container max-w-5xl mx-auto max-h-screen h-screen">
        <Changelog />
        <Navbar />
        <Hero />
      </main>

      <div className="bg-white">
        <div className='container max-w-5xl mx-auto'>
          <Services />
        </div>
      </div>

      <div className="bg-[#000B28]">
        <div className='container max-w-5xl mx-auto'>
          <OurGoal />
        </div>
      </div>

      <div className="bg-white">
        <div className='container max-w-5xl mx-auto'>
          <HowItWorks />
          <hr />
          <ForWhom />
          <hr />
          <JoinWaitlist />
          <Footer />
        </div>
      </div>
    
    </>
  )
}
